# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Club',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Entreprise',
            },
        ),
        migrations.CreateModel(
            name='Federation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Fédération',
            },
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('category', models.CharField(choices=[('ADT', 'Adulte'), ('STD', 'Etudiant'), ('ENSIL', 'Etudiant ENSILiens'), ('CHA', 'Challenge inter-entreprise'), ('AAEE', "Ancien de l'ENSIL")], max_length=10, verbose_name='Catégorie de coureur')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relais.Company', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Individuel',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('ESP', 'Espèce'), ('CHQ', 'Chèque'), ('PAY', 'Paypal'), ('N/A', 'Inconn')], max_length=10, verbose_name='Méthode')),
                ('state', models.BooleanField(default=False, verbose_name='Validé')),
                ('token', models.CharField(default='mqSlUfLLtmNP', editable=False, max_length=30, verbose_name='Token')),
                ('time', models.DateTimeField(auto_now=True)),
                ('ipn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipn.PayPalIPN')),
            ],
            options={
                'verbose_name': 'Paiement',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.CharField(choices=[('IND', 'Individuel'), ('GRP', 'Equipe de 3 personnes')], max_length=10, verbose_name='Type de coureur')),
                ('who', models.CharField(choices=[('ADT', 'Adulte'), ('STD', 'Etudiant'), ('ENSIL', 'Etudiant ENSILiens'), ('CHA', 'Challenge inter-entreprise'), ('AAEE', "Ancien de l'ENSIL")], max_length=10, verbose_name='Catégorie du coureur')),
                ('when', models.CharField(choices=[('PRE', 'En ligne'), ('J', 'Sur place')], max_length=10, verbose_name='Quand')),
                ('price', models.IntegerField(verbose_name='Prix')),
            ],
            options={
                'verbose_name_plural': 'Prix',
                'verbose_name': 'Prix',
            },
        ),
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=30, verbose_name='Nom')),
                ('gender', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=1, verbose_name='Sexe')),
                ('birthday', models.DateField(verbose_name='Date de naissance')),
                ('license_nb', models.CharField(blank=True, max_length=30, null=True, verbose_name='Numéro de licence')),
                ('canicross', models.BooleanField(default=False, verbose_name='Canicross')),
                ('tshirt', models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=4, null=True, verbose_name='Taille tshirt')),
                ('certificat', models.BooleanField(default=False, verbose_name='Certificat médical')),
                ('legal_status', models.BooleanField(default=False, verbose_name='Status légal')),
                ('num', models.PositiveIntegerField(help_text='Pour obtenir les derniers dossards, laisser vide', unique=True, verbose_name='Numéro de dossard')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Temps')),
                ('ready', models.BooleanField(default=False, verbose_name='Prêt à courir')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relais.Club', verbose_name='Club')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relais.Company', verbose_name='Entreprise')),
                ('federation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relais.Federation', verbose_name='Fédération')),
            ],
            options={
                'verbose_name': 'Coureur',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Ecole',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email pour inscription')),
                ('email_contact', models.EmailField(max_length=254, verbose_name='Email de contact')),
                ('url', models.URLField(verbose_name="URL du module d'inscription")),
                ('url_home', models.URLField(verbose_name='URL vers le site')),
                ('phone', models.CharField(max_length=14, verbose_name='Téléphone')),
                ('first_event', models.DateTimeField(verbose_name='Date première édition')),
                ('event', models.DateTimeField(verbose_name="Date de l'édition")),
                ('closure_postal', models.DateTimeField(verbose_name='Fin des inscriptions par voie postale')),
                ('open_online', models.DateTimeField(verbose_name='Ouverture des inscriptions en ligne')),
                ('closure_online', models.DateTimeField(verbose_name='Fermeture des inscriptions en ligne')),
                ('rule', models.TextField(verbose_name='Règlement')),
                ('disclamer', models.TextField(verbose_name='Décharge de responsabilité')),
                ('postal_address', models.TextField(verbose_name='Adresse postale')),
            ],
            options={
                'verbose_name': 'Configuration',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('category', models.CharField(choices=[('ADT', 'Adulte'), ('STD', 'Etudiant'), ('ENSIL', 'Etudiant ENSILiens'), ('CHA', 'Challenge inter-entreprise'), ('AAEE', "Ancien de l'ENSIL")], max_length=10, verbose_name='Catégorie du coureur')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relais.Company', verbose_name='Entreprise')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='relais.Payment', verbose_name='Paiement')),
                ('runner_1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_runner_1', to='relais.Runner', verbose_name='1er coureur')),
                ('runner_2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_runner_2', to='relais.Runner', verbose_name='2nd coureur')),
                ('runner_3', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_runner_3', to='relais.Runner', verbose_name='3eme coureur')),
            ],
            options={
                'verbose_name': 'Equipe',
            },
        ),
        migrations.AddField(
            model_name='runner',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relais.School', verbose_name='Ecole'),
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together=set([('config', 'who', 'when')]),
        ),
        migrations.AddField(
            model_name='payment',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relais.Price', verbose_name='Prix'),
        ),
        migrations.AddField(
            model_name='individual',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='relais.Payment', verbose_name='Paiement'),
        ),
        migrations.AddField(
            model_name='individual',
            name='runner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='relais.Runner', verbose_name='Coureur'),
        ),
        migrations.AlterUniqueTogether(
            name='runner',
            unique_together=set([('first_name', 'last_name', 'birthday', 'gender')]),
        ),
    ]
