# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date et heure du départ de la course'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('ESP', 'Espèce'), ('CHQ', 'Chèque'), ('PAY', 'Paypal'), ('N/A', 'Inconnu')], max_length=10, verbose_name='Méthode'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='token',
            field=models.CharField(default='NoRloV6CGQ8w', editable=False, max_length=30, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='runner',
            name='time',
            field=models.DurationField(blank=True, null=True, verbose_name='Temps'),
        ),
    ]
