# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-01 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relais', '0002_auto_20161123_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runner',
            name='canicross',
        ),
        migrations.AlterField(
            model_name='payment',
            name='token',
            field=models.CharField(default='IYvm1kQh7NHf', editable=False, max_length=30, verbose_name='Token'),
        ),
    ]
