# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-28 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relais', '0003_auto_20170201_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='category',
            field=models.CharField(choices=[('ADT', 'Adulte'), ('STD', 'Etudiant'), ('ENSIL-ENSCI', 'Etudiant ENSIL-ENSCI'), ('CHA', 'Challenge inter-entreprise'), ('AAEE / AAAEE', "Ancien de l'ENSIL-ENSCI - ENSCI")], max_length=10, verbose_name='Catégorie de coureur'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='token',
            field=models.CharField(default='ECv8JKXs6t4K', editable=False, max_length=30, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='price',
            name='config',
            field=models.CharField(choices=[('IND', 'Individuel'), ('GRP', 'Equipe de 3 personnes')], max_length=12, verbose_name='Type de coureur'),
        ),
        migrations.AlterField(
            model_name='price',
            name='who',
            field=models.CharField(choices=[('ADT', 'Adulte'), ('STD', 'Etudiant'), ('ENSIL-ENSCI', 'Etudiant ENSIL-ENSCI'), ('CHA', 'Challenge inter-entreprise'), ('AAEE / AAAEE', "Ancien de l'ENSIL-ENSCI - ENSCI")], max_length=12, verbose_name='Catégorie du coureur'),
        ),
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(choices=[('ADT', 'Adulte'), ('STD', 'Etudiant'), ('ENSIL-ENSCI', 'Etudiant ENSIL-ENSCI'), ('CHA', 'Challenge inter-entreprise'), ('AAEE / AAAEE', "Ancien de l'ENSIL-ENSCI - ENSCI")], max_length=10, verbose_name='Catégorie du coureur'),
        ),
    ]
